# This file is generated by the BAML compiler.
# Do not edit this file directly.
# Instead, edit the BAML files and recompile.

# ruff: noqa: E501,F401
# flake8: noqa: E501,F401
# pylint: disable=unused-import,line-too-long
# fmt: off

from ..types.classes.cls_instructions import Instructions
from ..types.partial.classes.cls_instructions import PartialInstructions
from baml_core.stream import AsyncStream
from typing import Callable, Protocol, runtime_checkable


import typing

import pytest
from contextlib import contextmanager
from unittest import mock

ImplName = typing.Literal["V1"]

T = typing.TypeVar("T", bound=typing.Callable[..., typing.Any])
CLS = typing.TypeVar("CLS", bound=type)


IProcessInstructionsOutput = Instructions

@runtime_checkable
class IProcessInstructions(Protocol):
    """
    This is the interface for a function.

    Args:
        query: str
        answer: str

    Returns:
        Instructions
    """

    async def __call__(self, *, query: str, answer: str) -> Instructions:
        ...

   

@runtime_checkable
class IProcessInstructionsStream(Protocol):
    """
    This is the interface for a stream function.

    Args:
        query: str
        answer: str

    Returns:
        AsyncStream[Instructions, PartialInstructions]
    """

    def __call__(self, *, query: str, answer: str
) -> AsyncStream[Instructions, PartialInstructions]:
        ...
class BAMLProcessInstructionsImpl:
    async def run(self, *, query: str, answer: str) -> Instructions:
        ...
    
    def stream(self, *, query: str, answer: str
) -> AsyncStream[Instructions, PartialInstructions]:
        ...

class IBAMLProcessInstructions:
    def register_impl(
        self, name: ImplName
    ) -> typing.Callable[[IProcessInstructions, IProcessInstructionsStream], None]:
        ...

    async def __call__(self, *, query: str, answer: str) -> Instructions:
        ...

    def stream(self, *, query: str, answer: str
) -> AsyncStream[Instructions, PartialInstructions]:
        ...

    def get_impl(self, name: ImplName) -> BAMLProcessInstructionsImpl:
        ...

    @contextmanager
    def mock(self) -> typing.Generator[mock.AsyncMock, None, None]:
        """
        Utility for mocking the ProcessInstructionsInterface.

        Usage:
            ```python
            # All implementations are mocked.

            async def test_logic() -> None:
                with baml.ProcessInstructions.mock() as mocked:
                    mocked.return_value = ...
                    result = await ProcessInstructionsImpl(...)
                    assert mocked.called
            ```
        """
        ...

    @typing.overload
    def test(self, test_function: T) -> T:
        """
        Provides a pytest.mark.parametrize decorator to facilitate testing different implementations of
        the ProcessInstructionsInterface.

        Args:
            test_function : T
                The test function to be decorated.

        Usage:
            ```python
            # All implementations will be tested.

            @baml.ProcessInstructions.test
            async def test_logic(ProcessInstructionsImpl: IProcessInstructions) -> None:
                result = await ProcessInstructionsImpl(...)
            ```
        """
        ...

    @typing.overload
    def test(self, *, exclude_impl: typing.Iterable[ImplName] = [], stream: bool = False) -> pytest.MarkDecorator:
        """
        Provides a pytest.mark.parametrize decorator to facilitate testing different implementations of
        the ProcessInstructionsInterface.

        Args:
            exclude_impl : Iterable[ImplName]
                The names of the implementations to exclude from testing.
            stream: bool
                If set, will return a streamable version of the test function.

        Usage:
            ```python
            # All implementations except the given impl will be tested.

            @baml.ProcessInstructions.test(exclude_impl=["implname"])
            async def test_logic(ProcessInstructionsImpl: IProcessInstructions) -> None:
                result = await ProcessInstructionsImpl(...)
            ```

            ```python
            # Streamable version of the test function.

            @baml.ProcessInstructions.test(stream=True)
            async def test_logic(ProcessInstructionsImpl: IProcessInstructionsStream) -> None:
                async for result in ProcessInstructionsImpl(...):
                    ...
            ```
        """
        ...

    @typing.overload
    def test(self, test_class: typing.Type[CLS]) -> typing.Type[CLS]:
        """
        Provides a pytest.mark.parametrize decorator to facilitate testing different implementations of
        the ProcessInstructionsInterface.

        Args:
            test_class : Type[CLS]
                The test class to be decorated.

        Usage:
        ```python
        # All implementations will be tested in every test method.

        @baml.ProcessInstructions.test
        class TestClass:
            def test_a(self, ProcessInstructionsImpl: IProcessInstructions) -> None:
                ...
            def test_b(self, ProcessInstructionsImpl: IProcessInstructions) -> None:
                ...
        ```
        """
        ...

BAMLProcessInstructions: IBAMLProcessInstructions
